### ISSUE TITLE
Not compatible with latest ecto version

### ISSUE THREAD

**Issue by utkarshvaish9** [elixir-mongo/mongodb_ecto#173]
mongodb_ecto requires ecto version 2.1.0 while currently, we are working with ecto-3.1.3, which is causing the error. Please upgrade it to support the latest ecto

**Comment by scottmessinger** [comment]
@utkarshvaish9 I currently have a branch that works and am trying to contact one of the maintainers to switch over ownership.

https://github.com/commoncurriculum/mongodb_ecto/pull/2#issuecomment-877674728

**Comment by joeapearson** [comment]
We are now compatible with the latest ecto, albeit in early beta form.  Closing this issue.
