### ISSUE TITLE
Mongo v6 support and/or mongodb_driver

### ISSUE THREAD

**Issue by Tuxified** [elixir-mongo/mongodb_ecto#192]
Hi,

I came across https://hex.pm/packages/mongodb_driver which supports Mongo v6 and according to it's docs also supports mongodb_ecto package. However it seems like this package (mongodb_ecto) is using mongodb package for it's connection to Mongo. Is it possible to somehow switch out mondodb for mongodb_driver ? 

Thanks in advance,
Tonći

**Comment by scottmessinger** [comment]
That's the goal! We would love to switch over -- I just haven't reviewed the PR yet. It's #190. If you'd like, give that PR a try and let me know if it works! Definitely would welcome any help!

**Comment by mweidner037** [comment]
Completed in https://github.com/elixir-mongo/mongodb_ecto/pull/190 . The CI now tests against MongoDB 5.0, 6.0, and 7.0.
